/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 26-oct.-2024 20:43:36 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `tb_almacen` CASCADE
;

DROP TABLE IF EXISTS `tb_cajas` CASCADE
;

DROP TABLE IF EXISTS `tb_carrito` CASCADE
;

DROP TABLE IF EXISTS `tb_categorias` CASCADE
;

DROP TABLE IF EXISTS `tb_clientes` CASCADE
;

DROP TABLE IF EXISTS `tb_compras` CASCADE
;

DROP TABLE IF EXISTS `tb_conceptos_gastos` CASCADE
;

DROP TABLE IF EXISTS `tb_conversiones` CASCADE
;

DROP TABLE IF EXISTS `tb_gastos` CASCADE
;

DROP TABLE IF EXISTS `tb_metodos_pago` CASCADE
;

DROP TABLE IF EXISTS `tb_modulos` CASCADE
;

DROP TABLE IF EXISTS `tb_operaciones` CASCADE
;

DROP TABLE IF EXISTS `tb_permisos` CASCADE
;

DROP TABLE IF EXISTS `tb_precios` CASCADE
;

DROP TABLE IF EXISTS `tb_productos` CASCADE
;

DROP TABLE IF EXISTS `tb_proveedores` CASCADE
;

DROP TABLE IF EXISTS `tb_roles` CASCADE
;

DROP TABLE IF EXISTS `tb_sucursales` CASCADE
;

DROP TABLE IF EXISTS `tb_unidades` CASCADE
;

DROP TABLE IF EXISTS `tb_usuarios` CASCADE
;

DROP TABLE IF EXISTS `tb_ventas` CASCADE
;

/* Create Tables */

CREATE TABLE `tb_almacen`
(
	`id_almacen` INT NOT NULL AUTO_INCREMENT,
	`codigo` VARCHAR(50) NULL,
	`nombre` VARCHAR(50) NULL,
	`descripcion` TEXT NULL,
	`id_unidad_base` INT NULL,
	`stock` DECIMAL(10,2) NULL,
	`stock_minimo` DECIMAL(10,2) NULL,
	`stock_maximo` DECIMAL(10,2) NULL,
	`precio_compra` VARCHAR(50) NULL,
	`precio_venta` VARCHAR(50) NULL,
	`fecha_ingreso` DATE NULL,
	`imagen` TEXT NULL,
	`id_usuario` INT NULL,
	`id_categoria` INT NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_producto` BIT(1) NULL,
	CONSTRAINT `PK_tb_almacen` PRIMARY KEY (`id_almacen` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_cajas`
(
	`id_caja` INT NOT NULL AUTO_INCREMENT,
	`fecha_apertura` DATETIME NULL,
	`fecha_cierre` DATETIME NULL,
	`monto_inicial` DECIMAL(10,2) NULL,
	`monto_final` DECIMAL(10,2) NULL,
	`id_usuario` INT NULL,
	`id_sucursal` INT NULL,
	`estado_caja` BIT(1) NULL,
	CONSTRAINT `PK_tb_cajas` PRIMARY KEY (`id_caja` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_carrito`
(
	`id_carrito` INT NOT NULL AUTO_INCREMENT,
	`nro_venta` INT NULL,
	`id_almacen` INT NULL,
	`cantidad` INT NULL,
	`fyh_creacion` DATETIME(4) NULL,
	`fyh_actualizacion` DATETIME(4) NULL,
	`fyh_eliminacio` DATETIME NULL,
	`estado_carrito` BIT(1) NULL,
	CONSTRAINT `PK_tb_carrito` PRIMARY KEY (`id_carrito` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_categorias`
(
	`id_categoria` INT NOT NULL AUTO_INCREMENT,
	`nombre_categoria` VARCHAR(50) NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_categoria` BIT(1) NULL,
	CONSTRAINT `PK_tb_categorias` PRIMARY KEY (`id_categoria` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_clientes`
(
	`id_cliente` INT NOT NULL AUTO_INCREMENT,
	`nombre_cliente` VARCHAR(50) NULL,
	`nit_ci_cliente` VARCHAR(50) NULL,
	`celular_cliente` VARCHAR(10) NULL,
	`email_cliente` VARCHAR(50) NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME(4) NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_cliente` BIT(1) NULL,
	CONSTRAINT `PK_tb_clientes` PRIMARY KEY (`id_cliente` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_compras`
(
	`id_compra` INT NOT NULL AUTO_INCREMENT,
	`id_almacen` INT NULL,
	`nro_compra` INT NULL,
	`fecha_compra` DATE NULL,
	`id_proveedor` INT NULL,
	`comprobante` VARCHAR(50) NULL,
	`id_usuario` INT NULL,
	`precio_compra` VARCHAR(50) NULL,
	`id_metodo` INT NULL,
	`cantidad` INT NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_compra` BIT(1) NULL,
	CONSTRAINT `PK_tb_compras` PRIMARY KEY (`id_compra` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_conceptos_gastos`
(
	`id_concepto` INT NOT NULL AUTO_INCREMENT,
	`nombre_concepto` VARCHAR(50) NULL,
	`descripcion_concepto` TEXT NULL,
	`estado_concepto` BIT(1) NULL,
	CONSTRAINT `PK_tb_conceptos_gastos` PRIMARY KEY (`id_concepto` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_conversiones`
(
	`id_conversion` INT NOT NULL AUTO_INCREMENT,
	`id_unidad1` INT NULL,
	`id_unidad2` INT NULL,
	`factor` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_tb_conversiones` PRIMARY KEY (`id_conversion` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_gastos`
(
	`id_gasto` INT NOT NULL AUTO_INCREMENT,
	`fecha_gasto` DATETIME NULL,
	`id_concepto` INT NULL,
	`monto` DECIMAL(10,2) NULL,
	`id_metodo` INT NULL,
	`id_usuario` INT NULL,
	`id_sucursal` INT NULL,
	`factura_gasto` TEXT NULL,
	`estado_gasto` BIT(1) NULL,
	CONSTRAINT `PK_tb_gastos` PRIMARY KEY (`id_gasto` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_metodos_pago`
(
	`id_metodo` INT NOT NULL AUTO_INCREMENT,
	`nombre_metodo` VARCHAR(50) NULL,
	`descripcion_metodo` TEXT NULL,
	`estado_metodo` BIT(1) NULL,
	CONSTRAINT `PK_tb_metodos_pago` PRIMARY KEY (`id_metodo` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_modulos`
(
	`id_modulo` INT NOT NULL AUTO_INCREMENT,
	`nombre_modulo` VARCHAR(50) NULL,
	`descripcion_modulo` VARCHAR(50) NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_modulo` BIT(1) NULL,
	CONSTRAINT `PK_tb_modulos` PRIMARY KEY (`id_modulo` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_operaciones`
(
	`id_operacion` INT NOT NULL AUTO_INCREMENT,
	`nombre_operacion` VARCHAR(50) NULL,
	`id_modulo` INT NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_operacion` BIT(1) NULL,
	CONSTRAINT `PK_tb_operaciones` PRIMARY KEY (`id_operacion` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_permisos`
(
	`id_permiso` INT NOT NULL AUTO_INCREMENT,
	`id_rol` INT NULL,
	`id_operacion` INT NULL,
	CONSTRAINT `PK_tb_permisos` PRIMARY KEY (`id_permiso` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_precios`
(
	`id_precio` INT NOT NULL AUTO_INCREMENT,
	`precio` DECIMAL(10,2) NULL,
	`fyh_eliminacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_creacion` DATETIME NULL,
	`estado_precio` BIT(1) NULL,
	CONSTRAINT `PK_tb_precios` PRIMARY KEY (`id_precio` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_productos`
(
	`id_producto` INT NOT NULL AUTO_INCREMENT,
	`id_almacen` INT NULL,
	`id_unidad` INT NULL,
	`id_precio` INT NULL,
	CONSTRAINT `PK_tb_productos` PRIMARY KEY (`id_producto` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_proveedores`
(
	`id_proveedor` INT NOT NULL AUTO_INCREMENT,
	`nombre_proveedor` VARCHAR(50) NULL,
	`celular` VARCHAR(50) NULL,
	`telefono` VARCHAR(50) NULL,
	`empresa` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	`direccion` VARCHAR(4) NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME(4) NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_proveedor` BIT(1) NULL,
	CONSTRAINT `PK_tb_proveedores` PRIMARY KEY (`id_proveedor` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_roles`
(
	`id_rol` INT NOT NULL AUTO_INCREMENT,
	`rol` VARCHAR(50) NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_rol` BIT(1) NULL,
	CONSTRAINT `PK_tb_roles` PRIMARY KEY (`id_rol` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_sucursales`
(
	`id_sucursal` INT NOT NULL AUTO_INCREMENT,
	`nombre_sucursal` VARCHAR(50) NULL,
	`direccion_sucursal` VARCHAR(50) NULL,
	`ciudad_sucursal` VARCHAR(50) NULL,
	`cel_sucursal` VARCHAR(50) NULL,
	`gerente_id` INT NULL,
	`estado_sucursal` BIT(1) NULL,
	CONSTRAINT `PK_tb_sucursal` PRIMARY KEY (`id_sucursal` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_unidades`
(
	`id_unidad` INT NOT NULL AUTO_INCREMENT,
	`nombre_unidad` VARCHAR(50) NULL,
	`simbolo_unidad` VARCHAR(50) NULL,
	CONSTRAINT `PK_tb_unidades` PRIMARY KEY (`id_unidad` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_usuarios`
(
	`id_usuario` INT NOT NULL AUTO_INCREMENT,
	`nombres` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	`password_user` TEXT NULL,
	`token` VARCHAR(50) NULL,
	`id_rol` INT NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_usuario` BIT(1) NULL,
	CONSTRAINT `PK_tb_usuarios` PRIMARY KEY (`id_usuario` ASC)
)
ENGINE=InnoDB
;

CREATE TABLE `tb_ventas`
(
	`id_venta` INT NOT NULL AUTO_INCREMENT,
	`nro_venta` INT NOT NULL,
	`id_cliente` INT NULL,
	`total_pagado` DECIMAL(10,2) NULL,
	`id_metodo` INT NULL,
	`id_usuario` INT NULL,
	`id_caja` INT NULL,
	`fyh_creacion` DATETIME NULL,
	`fyh_actualizacion` DATETIME NULL,
	`fyh_eliminacion` DATETIME NULL,
	`estado_venta` BIT(1) NULL,
	CONSTRAINT `PK_tb_ventas` PRIMARY KEY (`id_venta` ASC)
)
ENGINE=InnoDB
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `tb_almacen` 
 ADD INDEX `IXFK_tb_almacen_tb_categorias` (`id_categoria` ASC)
;

ALTER TABLE `tb_almacen` 
 ADD INDEX `IXFK_tb_almacen_tb_unidades` (`id_unidad_base` ASC)
;

ALTER TABLE `tb_almacen` 
 ADD INDEX `IXFK_tb_almacen_tb_usuarios` (`id_usuario` ASC)
;

ALTER TABLE `tb_cajas` 
 ADD INDEX `IXFK_tb_cajas_tb_sucursal` (`id_sucursal` ASC)
;

ALTER TABLE `tb_cajas` 
 ADD INDEX `IXFK_tb_cajas_tb_usuarios` (`id_usuario` ASC)
;

ALTER TABLE `tb_carrito` 
 ADD INDEX `IXFK_tb_carrito_tb_almacen` (`id_almacen` ASC)
;

ALTER TABLE `tb_compras` 
 ADD INDEX `IXFK_tb_compras_tb_almacen` (`id_almacen` ASC)
;

ALTER TABLE `tb_compras` 
 ADD INDEX `IXFK_tb_compras_tb_metodos_pago` (`id_metodo` ASC)
;

ALTER TABLE `tb_compras` 
 ADD INDEX `IXFK_tb_compras_tb_proveedores` (`id_proveedor` ASC)
;

ALTER TABLE `tb_compras` 
 ADD INDEX `IXFK_tb_compras_tb_usuarios` (`id_usuario` ASC)
;

ALTER TABLE `tb_conversiones` 
 ADD INDEX `IXFK_tb_conversiones_tb_unidades` (`id_unidad1` ASC)
;

ALTER TABLE `tb_conversiones` 
 ADD INDEX `IXFK_tb_conversiones_tb_unidades_02` (`id_unidad2` ASC)
;

ALTER TABLE `tb_gastos` 
 ADD INDEX `IXFK_tb_gastos_tb_conceptos_gastos` (`id_concepto` ASC)
;

ALTER TABLE `tb_gastos` 
 ADD INDEX `IXFK_tb_gastos_tb_metodos_pago` (`id_metodo` ASC)
;

ALTER TABLE `tb_gastos` 
 ADD INDEX `IXFK_tb_gastos_tb_usuarios` (`id_usuario` ASC)
;

ALTER TABLE `tb_operaciones` 
 ADD INDEX `IXFK_tb_operaciones_tb_modulos` (`id_modulo` ASC)
;

ALTER TABLE `tb_permisos` 
 ADD INDEX `IXFK_tb_permisos_tb_operaciones` (`id_operacion` ASC)
;

ALTER TABLE `tb_permisos` 
 ADD INDEX `IXFK_tb_permisos_tb_roles` (`id_rol` ASC)
;

ALTER TABLE `tb_productos` 
 ADD INDEX `IXFK_tb_productos_tb_almacen` (`id_almacen` ASC)
;

ALTER TABLE `tb_productos` 
 ADD INDEX `IXFK_tb_productos_tb_precios` (`id_precio` ASC)
;

ALTER TABLE `tb_productos` 
 ADD INDEX `IXFK_tb_productos_tb_unidades` (`id_unidad` ASC)
;

ALTER TABLE `tb_sucursales` 
 ADD INDEX `IXFK_tb_sucursal_tb_usuarios` (`gerente_id` ASC)
;

ALTER TABLE `tb_usuarios` 
 ADD INDEX `IXFK_tb_usuarios_tb_roles` (`id_rol` ASC)
;

ALTER TABLE `tb_ventas` 
 ADD INDEX `IXFK_tb_ventas_tb_cajas` (`id_caja` ASC)
;

ALTER TABLE `tb_ventas` 
 ADD INDEX `IXFK_tb_ventas_tb_clientes` (`id_cliente` ASC)
;

ALTER TABLE `tb_ventas` 
 ADD INDEX `IXFK_tb_ventas_tb_metodos_pago` (`id_metodo` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `tb_almacen` 
 ADD CONSTRAINT `FK_tb_almacen_tb_categorias`
	FOREIGN KEY (`id_categoria`) REFERENCES `tb_categorias` (`id_categoria`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_almacen` 
 ADD CONSTRAINT `FK_tb_almacen_tb_unidades`
	FOREIGN KEY (`id_unidad_base`) REFERENCES `tb_unidades` (`id_unidad`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_almacen` 
 ADD CONSTRAINT `FK_tb_almacen_tb_usuarios`
	FOREIGN KEY (`id_usuario`) REFERENCES `tb_usuarios` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_cajas` 
 ADD CONSTRAINT `FK_tb_cajas_tb_sucursal`
	FOREIGN KEY (`id_sucursal`) REFERENCES `tb_sucursales` (`id_sucursal`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_cajas` 
 ADD CONSTRAINT `FK_tb_cajas_tb_usuarios`
	FOREIGN KEY (`id_usuario`) REFERENCES `tb_usuarios` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_carrito` 
 ADD CONSTRAINT `FK_tb_carrito_tb_almacen`
	FOREIGN KEY (`id_almacen`) REFERENCES `tb_almacen` (`id_almacen`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_compras` 
 ADD CONSTRAINT `FK_tb_compras_tb_almacen`
	FOREIGN KEY (`id_almacen`) REFERENCES `tb_almacen` (`id_almacen`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_compras` 
 ADD CONSTRAINT `FK_tb_compras_tb_metodos_pago`
	FOREIGN KEY (`id_metodo`) REFERENCES `tb_metodos_pago` (`id_metodo`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_compras` 
 ADD CONSTRAINT `FK_tb_compras_tb_proveedores`
	FOREIGN KEY (`id_proveedor`) REFERENCES `tb_proveedores` (`id_proveedor`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_compras` 
 ADD CONSTRAINT `FK_tb_compras_tb_usuarios`
	FOREIGN KEY (`id_usuario`) REFERENCES `tb_usuarios` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_conversiones` 
 ADD CONSTRAINT `FK_tb_conversiones_tb_unidades`
	FOREIGN KEY (`id_unidad1`) REFERENCES `tb_unidades` (`id_unidad`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_conversiones` 
 ADD CONSTRAINT `FK_tb_conversiones_tb_unidades_02`
	FOREIGN KEY (`id_unidad2`) REFERENCES `tb_unidades` (`id_unidad`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_gastos` 
 ADD CONSTRAINT `FK_tb_gastos_tb_conceptos_gastos`
	FOREIGN KEY (`id_concepto`) REFERENCES `tb_conceptos_gastos` (`id_concepto`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_gastos` 
 ADD CONSTRAINT `FK_tb_gastos_tb_metodos_pago`
	FOREIGN KEY (`id_metodo`) REFERENCES `tb_metodos_pago` (`id_metodo`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_gastos` 
 ADD CONSTRAINT `FK_tb_gastos_tb_usuarios`
	FOREIGN KEY (`id_usuario`) REFERENCES `tb_usuarios` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_operaciones` 
 ADD CONSTRAINT `FK_tb_operaciones_tb_modulos`
	FOREIGN KEY (`id_modulo`) REFERENCES `tb_modulos` (`id_modulo`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_permisos` 
 ADD CONSTRAINT `FK_tb_permisos_tb_operaciones`
	FOREIGN KEY (`id_operacion`) REFERENCES `tb_operaciones` (`id_operacion`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_permisos` 
 ADD CONSTRAINT `FK_tb_permisos_tb_roles`
	FOREIGN KEY (`id_rol`) REFERENCES `tb_roles` (`id_rol`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_productos` 
 ADD CONSTRAINT `FK_tb_productos_tb_almacen`
	FOREIGN KEY (`id_almacen`) REFERENCES `tb_almacen` (`id_almacen`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_productos` 
 ADD CONSTRAINT `FK_tb_productos_tb_precios`
	FOREIGN KEY (`id_precio`) REFERENCES `tb_precios` (`id_precio`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_productos` 
 ADD CONSTRAINT `FK_tb_productos_tb_unidades`
	FOREIGN KEY (`id_unidad`) REFERENCES `tb_unidades` (`id_unidad`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_sucursales` 
 ADD CONSTRAINT `FK_tb_sucursal_tb_usuarios`
	FOREIGN KEY (`gerente_id`) REFERENCES `tb_usuarios` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_usuarios` 
 ADD CONSTRAINT `FK_tb_usuarios_tb_roles`
	FOREIGN KEY (`id_rol`) REFERENCES `tb_roles` (`id_rol`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_ventas` 
 ADD CONSTRAINT `FK_tb_ventas_tb_clientes`
	FOREIGN KEY (`id_cliente`) REFERENCES `tb_clientes` (`id_cliente`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `tb_ventas` 
 ADD CONSTRAINT `FK_tb_ventas_tb_metodos_pago`
	FOREIGN KEY (`id_metodo`) REFERENCES `tb_metodos_pago` (`id_metodo`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
